image:
  file: .gitpod.Dockerfile
checkoutLocation: '.'
tasks:
  - name: Clean root and grab useful exercises.
    before: |
      rm -rfv *
      rm -rf .git
      rm .gitpod*
      sudo mv /home/gitpod/cicd-exercises/* .
      git init
      git add .
      git commit -m "Initial commit"
      exit 0

vscode:
  settings:
    "files.exclude": {
      "**/.gitpod": true,
      "**/.pyenv_mirror": true,
      "**/.vscode-remote": true
    }